service: microserverless-sample

provider:
  name: aws
  runtime: provided
  region: us-west-2

package:
  individually: true
  artifact: bin/Release/netcoreapp3.1/MicroServerless.Sample.zip
  
functions:
  sample:
    handler: MicroServerless::MicroServerless.Sample.Progam::Main
    events:
      - http:
          path: /
          method: ANY